apiVersion: v1
kind: Pod
metadata:
  name: vaultadmin
spec:
  containers:
  - image: cfmanteiga/alpine-bash-curl-jq
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
    name: vaultadmin
  restartPolicy: Always