[[constraint]]
  name = "k8s.io/api"
  version = "kubernetes-1.12.2"

[[constraint]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.12.2"

[[constraint]]
  name = "k8s.io/client-go"
  version = "9.0.0"

[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/nginxinc/nginx-plus-go-sdk"
  version = "0.2.0"
