apiVersion: v1
kind: Pod
metadata:
  name: myapp
spec:
  containers:
  - image: cfmanteiga/alpine-bash-curl-jq
    command:
    - sleep
    - "3600"
    imagePullPolicy: IfNotPresent
    name: myapp
  restartPolicy: Always