apiVersion: v1
kind: Service
metadata:
  name: vault-demo
  labels:
    app: vault-demo
spec:
  ports:
  - name: http
    port: 8080
  selector:
    app: vault-demo
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: vault-demo
spec:
  rules:
  - host: vault-demo.mycompany.io
    http:
      paths:
      - path: /
        backend:
          serviceName: vault-demo
          servicePort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: vault-demo
  name: vault-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vault-demo
  template:
    metadata:
      labels:
        app: vault-demo
    spec:
      containers:
      - image: vault-demo:latest
        name: vault-demo
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP


