apiVersion: v1
kind: Service
metadata:
  labels:
    app: vault-demo
  name: vault-demo
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: vault-demo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: vault-demo
  name: vault-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vault-demo
  template:
    metadata:
      labels:
        app: vault-demo
    spec:
      containers:
      - image: vault-demo:latest
        name: vault-demo
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
          name: vaultport
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 3 


