apiVersion: v1
kind: Service
metadata:
  labels:
    app: spring-native-example
  name: spring-native-example 
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: spring-native-example
---
apiVersion: v1
kind: DeploymentConfig
metadata:
  name: spring-native-example
spec:
  triggers:
    -
      type: ConfigChange
    -
      type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
          - spring-native-example
        from:
          kind: ImageStreamTag
          namespace: spring-native-example
          name: 'spring-native-example:latest'
  replicas: 1
  template:
    metadata:
      labels:
        app: spring-native-example       
    spec:
      initContainers:
      - name: pem-to-truststore
        image: registry.access.redhat.com/redhat-sso-7/sso71-openshift:1.1-16
        env:
          - name: ca_bundle
            value: /var/run/secrets/kubernetes.io/serviceaccount/service-ca.crt
          - name: truststore_jks
            value: /var/run/secrets/java.io/keystores/truststore.jks
          - name: password
            value: changeit    
        command: ['/bin/bash']
        args: ['-c', "csplit -z -f crt- $ca_bundle '/-----BEGIN CERTIFICATE-----/' '{*}' && for file in crt-*; do keytool -import -noprompt -keystore $truststore_jks -file $file -storepass changeit -alias service-$file; done"]
        volumeMounts:
          - name: keystore-volume
            mountPath: /var/run/secrets/java.io/keystores      
      containers:
        - name: spring-native-example
          image: "spring-native-example/spring-native-example:latest"
          imagePullPolicy: Always
          env:     
          - name: JAVA_OPTIONS
            value: -Djavax.net.ssl.trustStore=/var/run/secrets/java.io/keystores/truststore.jks -Djavax.net.ssl.trustStorePassword=changeit                 
          - name: "VAULT_HOST"
            value: "vault.vault-controller.svc"
          - name: "VAULT_PORT"
            value: "8200"           
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 3 
          volumeMounts:
          - name: keystore-volume
            mountPath: /var/run/secrets/java.io/keystores            
      volumes:
      - name: keystore-volume
        emptyDir: {}                                                              
